### ISSUE TITLE
[Tracker] Repo reorganization

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/.github#62]
Original note: https://docs.google.com/document/d/1g4wEiZa4uhaBDIzBk7DLb1JRA89rrv4p2OXo0VK66K0/edit#

Planned maintenance: @gkc and @XavierChanth aim to complete over the weekend of July 1st.

# Repos and Packages

The main problem with cross repo deps right now is between at_tools and at_libraries:

(on the left is at_tools, on the right is at_libraries)

Original notes:
I propose that we move at_commons and at_utils to at_libraries, this would make it so that at_libraries contains the things we depend on, and limit at_tools to niche cases where packages are depended on.

Beyond that the sshnoports repo can become something along the lines of “no ports oss” and add a package folder to the repo.

at_talk could be moved to at_tools.

at_lorawan could be moved to at_services?

Reasoning for these changes: to make things more maintainable in at_mono, and the org in general.

See page 2 for proposed next steps

Post Changes Repo purposes:
At_tools - products and close to products
At_dev_tools - developer tools
At_libraries - dependencies and libraries
At_demos - demo code

Next steps:
Packages currently in at_tools move to at_libraries (at_utils + at_commons)
Rename at_tools to at_dev_tools 
(at_cram, at_pkam, at_cli, at_hive_rec., at_ve_doc., at_dump_atKeys)
Rename sshnoports repo to at_tools
Refactor sshnoports to have a packages folder
Rename current at_demos repo to at_demos_archive and archive it
Create new at_demos repo
Move at_talk to at_demos
Move at_lorawan to at_demos

```[tasklist]
### Tasks
- [ ] https://github.com/atsign-foundation/at_libraries/issues/359
- [ ] https://github.com/atsign-foundation/at_libraries/issues/360
```

---

## Summary of the work done
- Import at_utils to at_libraries (PR 1)
- Import at_commons to at_libraries (PR 2)
- Import Murali's PR to at_libaries (PR 3, It was ready for review so I think it can be merged)
- Update the at_libraries README with at_utils and at_commons descriptions
- Remove at_commons and at_utils from at_tools
  - [!] Before we merge this we should update the repo URL on pub.dev

```[tasklist]
### Next Steps (PRs to Review)
- [ ] https://github.com/atsign-foundation/at_libraries/pull/369
- [ ] https://github.com/atsign-foundation/at_libraries/pull/370
- [ ] https://github.com/atsign-foundation/at_libraries/pull/371
- [ ] https://github.com/atsign-foundation/at_libraries/pull/372
- [ ] https://github.com/atsign-foundation/at_libraries/pull/373
- [x] Republish at_commons and at_utils
- [ ] https://github.com/atsign-foundation/at_tools/pull/347
```

**Comment by xavierchanth** [comment]
### Export from at_tools

Tracking everything very carefully here:

From trunk of at_tools:
```sh
git subtree split -P packages/at_commons -b splitcommons
git subtree split -P packages/at_utils -b splitutils
```

@murali-shris also has an active branch (apkam_onboarding_changes) which I've done a split for:
```sh
git subtree split -P packages/at_commons -b splitcommonsapkam
```

### Import to at_libraries

Creating branches with the git history in at_libraries:

at_utils:
```sh
git checkout trunk
git checkout -b utils
git subtree add -P packages/at_utils git@github.com:atsign-foundation/at_tools.git splitutils
```

at_commons:
```sh
git checkout trunk
git checkout -b commons
git subtree add -P packages/at_commons git@github.com:atsign-foundation/at_tools.git splitcommons
```

Murali's branch:
```sh
git checkout trunk
git checkout -b commonsapkam
git subtree add -P packages/at_commons git@github.com:atsign-foundation/at_tools.git splitcommonsapkam
```


What's important to note is that these branches are using the same commits for their history... no duplicates (note the pink line):


![Image](https://github.com/atsign-foundation/.github/assets/33691921/c664cdec-c19c-49e4-a5b4-2c42e36b7768)

**Comment by xavierchanth** [comment]
This means that we are avoiding unnecessary merge conflicts with commonsapkam (i.e. murali's branch)

**Comment by xavierchanth** [comment]
Extracted part of at_tools README:
```md
(These libraries can also be found on pub.dev as linked)

### pub.dev packages

[at_commons](https://pub.dev/packages/at_commons) Commonly used components
in implementation of the atProtocol.

[at_utils](https://pub.dev/packages/at_utils) This is the Utility library
for atProtocol projects. It contains utility classes for atsign, atmetadata,
configuration and logger.
```

**Comment by xavierchanth** [comment]
All said and done, the packages themselves have their git histories copied, but the README and workflow was manually updated.

The workflow will likely cause a merge conflict since nearly the same changes were made on two different branches. It was unavoidable in order to have the tests in place for these PRs

**Comment by gkc** [comment]
Approved and merged https://github.com/atsign-foundation/at_libraries/pull/369
Resolved conflict in workflow file for https://github.com/atsign-foundation/at_libraries/pull/370/
Approved and merged https://github.com/atsign-foundation/at_libraries/pull/370/

**Comment by gkc** [comment]
Merged trunk into https://github.com/atsign-foundation/at_libraries/pull/372, tweaked readme, pushed, approved, merged

**Comment by gkc** [comment]
Merged trunk into https://github.com/atsign-foundation/at_libraries/pull/371, approved, merged
