### ISSUE TITLE
Add a Pana GitHub workflow

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/.github#65]
### Is your feature request related to a problem? Please describe.

Currently some of our packages have a pub score of less than 130 points and there isn't a GitHub workflow for us to check the pub score before merging a PR.

### Describe the solution you'd like

A GitHub workflow that will only allow PR's with a pub points of 130 or more to be merged on the below package repos.

```[tasklist]
### Packages to add [Pana WorkFlow](https://workflows.vgv.dev/docs/workflows/pana) to:
- [ ] [at_chat_flutter (140)](https://pub.dev/packages/at_chat_flutter)
- [ ] [at_location_flutter (60)](https://pub.dev/packages/at_location_flutter)
- [ ] [at_contact (80)](https://pub.dev/packages/at_contact)
- [ ] [at_contacts_groups_flutter (60)](https://pub.dev/packages/at_contacts_group_flutter)
- [ ] [at_follows_flutter (70)](https://pub.dev/packages/at_follows_flutter)
- [ ] [at_invitation_flutter (70)](https://pub.dev/packages/at_invitation_flutter)
- [ ] [at_notify_flutter (70)](https://pub.dev/packages/at_notify_flutter)
- [ ] [at_events_flutter (90)](https://pub.dev/packages/at_events_flutter)
- [ ] [at_pkam (100)](https://pub.dev/packages/at_pkam/score)
- [ ] [at_onboarding_flutter (110)](https://pub.dev/packages/at_onboarding_flutter)
- [ ] [at_server_status (110)](https://pub.dev/packages/at_server_status)
- [ ] [at_app_bundler (110)](https://pub.dev/packages/at_app_bundler)
- [ ] [max30101 (110)](https://pub.dev/packages/max30101)
- [ ] at_commons (130)
- [ ] at_client_mobile (130)
- [ ] at_common_flutter (130)
- [ ] at_contacts_flutter (120)
- [ ] at_backupkey_flutter (120)
- [ ] at_onboarding_cli (120)
- [ ] at_cli (120)
- [ ] at_sync_ui_flutter (120)
- [ ] at_theme_flutter (120)
- [ ] at_viz (120)
- [ ] at_app (125)
- [ ] at_app_create (130)
```

```[tasklist]
### Tasks
```

**Comment by cpswan** [comment]
@CurtlyCritchlow I think initially this shouldn't be a mandatory check, but once we've got some experience of using it then we can decide to make it mandatory (perhaps starting with packages that pass, and then working our way through those that don't).

Can you please pick a repos to start implementation, and once you're happy with it I can use git-xargs to roll out the workflow to the other repos in the list.
