### ISSUE TITLE
Better dependency tree verification

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/.github#71]
```[tasklist]
### Tasks
- [ ] Add local dependency checks to our other repos like in https://github.com/atsign-foundation/at_widgets/pull/740
- [ ] Add downstream checkers to alert when downstream dependencies need to be updated
- [ ] Maybe add an "all-seeing" one to at_mono which can be called from other repos
```
